package mcp

import "github.com/mark3labs/mcp-go/mcp"

// allTools returns every MCP tool exposed by the PinchTab MCP server.
func allTools() []mcp.Tool {
	return []mcp.Tool{
		// ── Navigation ──────────────────────────────────────────────
		mcp.NewTool("pinchtab_navigate",
			mcp.WithDescription("Navigate to a URL in the browser"),
			mcp.WithString("url", mcp.Required(), mcp.Description("The URL to navigate to")),
			mcp.WithString("tabId", mcp.Description("Target tab ID (optional, uses current tab if empty)")),
		),
		mcp.NewTool("pinchtab_snapshot",
			mcp.WithDescription("Get an accessibility tree snapshot of the current page"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("interactive", mcp.Description("Only interactive elements (buttons, links, inputs)")),
			mcp.WithBoolean("compact", mcp.Description("Compact format (most token-efficient)")),
			mcp.WithString("format", mcp.Description("Output format: 'compact' or 'text'")),
			mcp.WithBoolean("diff", mcp.Description("Only changes since last snapshot")),
			mcp.WithString("selector", mcp.Description("Unified selector to scope the snapshot (CSS, XPath, text, or ref)")),
			mcp.WithNumber("maxTokens", mcp.Description("Maximum estimated tokens in response (e.g. 300)")),
			mcp.WithNumber("depth", mcp.Description("Maximum tree depth (e.g. 3)")),
			mcp.WithBoolean("noAnimations", mcp.Description("Disable animations before capturing the snapshot")),
		),
		mcp.NewTool("pinchtab_screenshot",
			mcp.WithDescription("Take a screenshot of the current page"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithString("format", mcp.Description("Image format: 'jpeg' (default) or 'png'")),
			mcp.WithNumber("quality", mcp.Description("JPEG quality 0-100 (only for JPEG format)")),
		),
		mcp.NewTool("pinchtab_get_text",
			mcp.WithDescription("Extract readable text content from the current page"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("raw", mcp.Description("Return raw text without formatting")),
			mcp.WithString("format", mcp.Description("Response format: 'text'/'plain' for plain text, default JSON envelope")),
			mcp.WithNumber("maxChars", mcp.Description("Maximum characters in response (e.g. 3000)")),
		),

		// ── Interaction ─────────────────────────────────────────────
		mcp.NewTool("pinchtab_click",
			mcp.WithDescription("Click an element by selector (ref from snapshot e.g. 'e5', CSS e.g. 'css:#btn', XPath e.g. 'xpath://button', text e.g. 'text:Submit', or semantic e.g. 'find:login button')"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector: ref (e.g. 'e5'), CSS ('css:#btn' or '#btn'), XPath ('xpath://button'), text ('text:Submit'), or semantic ('find:login button')")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithBoolean("waitNav", mcp.Description("Wait for navigation after the click when the element triggers a page change")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_type",
			mcp.WithDescription("Type text into an input element"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to type")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_press",
			mcp.WithDescription("Press a keyboard key (Enter, Tab, Escape, etc.)"),
			mcp.WithString("key", mcp.Required(), mcp.Description("Key to press (e.g., 'Enter', 'Tab', 'Escape')")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_hover",
			mcp.WithDescription("Hover over an element"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_focus",
			mcp.WithDescription("Focus an element"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_select",
			mcp.WithDescription("Select a dropdown option by value"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector for the select element")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("value", mcp.Required(), mcp.Description("Option value to select")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_scroll",
			mcp.WithDescription("Scroll the page or an element"),
			mcp.WithString("selector", mcp.Description("Unified selector for element to scroll (omit for page scroll)")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref to scroll — use 'selector' instead")),
			mcp.WithNumber("pixels", mcp.Description("Number of pixels to scroll (positive=down, negative=up)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_fill",
			mcp.WithDescription("Fill an input field directly via JavaScript dispatch"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref — use 'selector' instead")),
			mcp.WithString("value", mcp.Required(), mcp.Description("Value to fill")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Keyboard (no selector — targets focused element) ────────
		mcp.NewTool("pinchtab_keyboard_type",
			mcp.WithDescription("Type text at the currently focused element via keystroke events (keyDown + keyUp per character)"),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to type")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_keyboard_inserttext",
			mcp.WithDescription("Insert text at the currently focused element without key events (paste-like)"),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to insert")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_keydown",
			mcp.WithDescription("Hold a key down (e.g. modifier keys like Control, Shift, Alt)"),
			mcp.WithString("key", mcp.Required(), mcp.Description("Key to hold down (e.g. 'Control', 'Shift', 'Alt', 'a')")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_keyup",
			mcp.WithDescription("Release a held key"),
			mcp.WithString("key", mcp.Required(), mcp.Description("Key to release (e.g. 'Control', 'Shift', 'Alt', 'a')")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Content ─────────────────────────────────────────────────
		mcp.NewTool("pinchtab_eval",
			mcp.WithDescription("Execute JavaScript in the browser and return the result"),
			mcp.WithString("expression", mcp.Required(), mcp.Description("JavaScript expression to evaluate")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_pdf",
			mcp.WithDescription("Export the current page as a PDF (returns base64-encoded PDF)"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("landscape", mcp.Description("Landscape orientation")),
			mcp.WithNumber("scale", mcp.Description("Print scale 0.1-2.0 (default: 1.0)")),
			mcp.WithString("pageRanges", mcp.Description("Pages to export (e.g., '1-3,5')")),
		),
		mcp.NewTool("pinchtab_find",
			mcp.WithDescription("Find elements by text content or CSS selector"),
			mcp.WithString("query", mcp.Required(), mcp.Description("Text or CSS selector to search for")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Tab Management ──────────────────────────────────────────
		mcp.NewTool("pinchtab_list_tabs",
			mcp.WithDescription("List all open browser tabs"),
		),
		mcp.NewTool("pinchtab_close_tab",
			mcp.WithDescription("Close a browser tab"),
			mcp.WithString("tabId", mcp.Description("ID of the tab to close")),
		),
		mcp.NewTool("pinchtab_health",
			mcp.WithDescription("Check PinchTab server health status"),
		),
		mcp.NewTool("pinchtab_cookies",
			mcp.WithDescription("Get cookies for the current page"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_connect_profile",
			mcp.WithDescription("Get the user-facing connect URL and instance status for a profile"),
			mcp.WithString("profile", mcp.Required(), mcp.Description("Profile name or profile ID")),
		),

		// ── Utility ─────────────────────────────────────────────────
		mcp.NewTool("pinchtab_wait",
			mcp.WithDescription("Wait for a specified number of milliseconds"),
			mcp.WithNumber("ms", mcp.Required(), mcp.Description("Milliseconds to wait (max 30000)")),
		),
		mcp.NewTool("pinchtab_wait_for_selector",
			mcp.WithDescription("Wait for an element matching a selector to appear or disappear on the page"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector to wait for (CSS, XPath, text, or ref)")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("state", mcp.Description("Element state to wait for: 'visible' (default) or 'hidden'")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_text",
			mcp.WithDescription("Wait for specific text to appear on the page"),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to wait for")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_url",
			mcp.WithDescription("Wait for the page URL to match a glob pattern"),
			mcp.WithString("url", mcp.Required(), mcp.Description("URL glob pattern to match (e.g. '**/dashboard')")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_load",
			mcp.WithDescription("Wait for a page load state (e.g. networkidle)"),
			mcp.WithString("load", mcp.Required(), mcp.Description("Load state to wait for: 'networkidle'")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_function",
			mcp.WithDescription("Wait for a JavaScript expression to return a truthy value"),
			mcp.WithString("fn", mcp.Required(), mcp.Description("JavaScript expression to evaluate")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Network Monitoring ──────────────────────────────────────
		mcp.NewTool("pinchtab_network",
			mcp.WithDescription("List recent network requests captured from the browser. Returns method, status, URL, type, size, and timing for each request."),
			mcp.WithString("tabId", mcp.Description("Target tab ID (optional, uses current tab if empty)")),
			mcp.WithString("filter", mcp.Description("URL pattern filter (substring match)")),
			mcp.WithString("method", mcp.Description("HTTP method filter (GET, POST, etc)")),
			mcp.WithString("status", mcp.Description("Status code range filter (e.g. '4xx', '5xx', '200')")),
			mcp.WithString("type", mcp.Description("Resource type filter (xhr, fetch, document, stylesheet, script, image, etc)")),
			mcp.WithNumber("limit", mcp.Description("Maximum number of entries to return")),
			mcp.WithNumber("bufferSize", mcp.Description("Per-tab buffer size for new capture (default from config, typically 100)")),
		),
		mcp.NewTool("pinchtab_network_detail",
			mcp.WithDescription("Get full details of a specific network request including headers, timing, and optionally the response body"),
			mcp.WithString("requestId", mcp.Required(), mcp.Description("The request ID from pinchtab_network results")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("body", mcp.Description("Include response body (can be large)")),
		),
		mcp.NewTool("pinchtab_network_clear",
			mcp.WithDescription("Clear captured network data for a tab or all tabs"),
			mcp.WithString("tabId", mcp.Description("Target tab ID (optional, clears all if empty)")),
		),

		// ── Dialog ──────────────────────────────────────────────────
		mcp.NewTool("pinchtab_dialog",
			mcp.WithDescription("Handle a JavaScript dialog (alert, confirm, prompt). Accept or dismiss the currently open dialog."),
			mcp.WithString("action", mcp.Required(), mcp.Description("Action to take: 'accept' or 'dismiss'")),
			mcp.WithString("text", mcp.Description("Text to enter for prompt dialogs (only used with accept)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
	}
}
